// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvjWSMvuBPygkXmNVZh32KcS3RM3i8WVU',
    appId: '1:457839484543:web:4fa72d0a4fc22e2ce3694a',
    messagingSenderId: '457839484543',
    projectId: 'fir-loginapp-ae7e3',
    authDomain: 'fir-loginapp-ae7e3.firebaseapp.com',
    storageBucket: 'fir-loginapp-ae7e3.appspot.com',
    measurementId: 'G-0D0DS5ZJKK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC53SNR3JL1bgCZd45wQnAN3CpR69zXdUg',
    appId: '1:457839484543:android:de1193d8e7d33da7e3694a',
    messagingSenderId: '457839484543',
    projectId: 'fir-loginapp-ae7e3',
    storageBucket: 'fir-loginapp-ae7e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwUzvOzh5HDYpOdR5kdbrkCUmox-8dheI',
    appId: '1:457839484543:ios:c081b0a05021521ae3694a',
    messagingSenderId: '457839484543',
    projectId: 'fir-loginapp-ae7e3',
    storageBucket: 'fir-loginapp-ae7e3.appspot.com',
    iosBundleId: 'com.example.firebaseLoginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwUzvOzh5HDYpOdR5kdbrkCUmox-8dheI',
    appId: '1:457839484543:ios:c081b0a05021521ae3694a',
    messagingSenderId: '457839484543',
    projectId: 'fir-loginapp-ae7e3',
    storageBucket: 'fir-loginapp-ae7e3.appspot.com',
    iosBundleId: 'com.example.firebaseLoginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvjWSMvuBPygkXmNVZh32KcS3RM3i8WVU',
    appId: '1:457839484543:web:ede0280e4ac71813e3694a',
    messagingSenderId: '457839484543',
    projectId: 'fir-loginapp-ae7e3',
    authDomain: 'fir-loginapp-ae7e3.firebaseapp.com',
    storageBucket: 'fir-loginapp-ae7e3.appspot.com',
    measurementId: 'G-PE543S6541',
  );
}
